# Init mongodb replica-set in a newly-deployed cluster !
apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init-job
  labels:
    app: mongodb
spec:
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-instance
        image: mongo:5
        command:
          - "mongosh"
          - "--host"
          - "mongodb-statefulset-0.mongodb-service"
          - "--eval"
          - "rs.initiate({
             _id: \"mongo_rs\",
             members: [
                { _id: 0, host: 'mongodb-statefulset-0.mongodb-service:27017', priority: 2 },
                { _id: 1, host: 'mongodb-statefulset-1.mongodb-service:27017', priority: 1 },
                { _id: 2, host: 'mongodb-statefulset-2.mongodb-service:27017', priority: 1 }
              ]
            })"
      restartPolicy: Never
  backoffLimit: 3