apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
  namespace: mongodb
spec:
  template:
    spec:
      containers:
      - name: mongo-init
        image: mongo:6.0
        command:
          - "sh"
          - "-c"
          - "until mongo --eval 'print(\"waited for connection\")'; do sleep 2; done"
      restartPolicy: Never
