apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  clusterIP: None  # Headless service
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongo