apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
  namespace: mongodb  # Or your desired namespace
spec:
  template:
    spec:
      containers:
      - name: mongo-init
        image: mongo:latest  # Or your preferred MongoDB image
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "Initializing MongoDB..."
          # Wait for the MongoDB service to be available
          until nslookup mongodb.$(cat /etc/resolv.conf | grep search | awk '{print $2}') > /dev/null 2>&1; do
            echo "Waiting for MongoDB service..."
            sleep 5
          done
          # Initialize the Replica Set (if needed, adjust for single instance)
          mongo mongodb:27017 --eval 'rs.initiate({ _id: "rs0", members: [ { _id: 0, host: "mongodb:27017" } ] })'
          echo "MongoDB initialized."
      restartPolicy: OnFailure
  backoffLimit: 4