apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo # Make sure this matches the labels on your MongoDB pods
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017