apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: default  # Ensure namespace consistency
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb  # This must match the service selector
  template:
    metadata:
      labels:
        app: mongodb  # This label should match the service selector
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          ports:
            - containerPort: 27017
