#Mongodb headless service to allow communication with specific mongodb pods
#Headless services advertise selected pod's IPs as DNS records
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - port: 27017