# Deploy mongodb
# Statefulset allows for persistence of previous pods metadata
# Statefulset is used here for persistent storage and DNS FQDNs
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
  labels:
    app: mongodb
spec:
  serviceName: "mongodb-service" # Specifies the service to use
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb-instance
          image: mongo:5
          command:
            - mongod
            - "--replSet"
            - mongo_rs
            - "--bind_ip_all"
            - "--port"
            - "27017"
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
  volumeClaimTemplates:
    # Allow storage persistence of pods, thanks to created SC
    - metadata:
        name: mongodb-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1G
        storageClassName: gp3-storage
