apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-storage
  #annotations:
    #argocd.argoproj.io/sync-wave: "0"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  type: gp2
