apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polybott-ingress
  namespace: default # Assuming your polybot-service is in the default namespace
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # Optional: Add TLS configuration if you want HTTPS
    # kubernetes.io/tls-acme: "true" # If using cert-manager for automatic TLS
    # cert-manager.io/issuer: "letsencrypt-prod"
spec:
  # Optional: TLS configuration
  # tls:
  # - hosts:
  #   - your-domain.com
  #   secretName: polybott-tls

  rules:
  - host: itsik-k8s-project-dns.devops-int-college.com
    http:
      paths:
      - path: /polybott
        pathType: Prefix
        backend:
          service:
            name: polybott-service
            port:
              number: 8443