apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
      labels:
        app: polybot
    spec:
      containers:
        - name: polybot
          image: docker.io/jeenge/polybot:f5a976e297c25e19173c1e88dca85b8612573a4b
          command:
            - python
            - app.py
          ports:
            - containerPort: 8443
          env:
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-manager
                  key: telegram_token
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: bucket_name
            - name: SQS_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: sqs_url
            - name: POLYBOT_RESULTS_URL
              value: http://svc-polybot:8443/
      imagePullSecrets:
        - name: dockerhub-secret
