apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-deployment
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
      labels:
        app: polybot
    spec:
      containers:
      - name: polybot
        image: docker.io/jeenge/polybot:21 # Explicit docker.io
        command: ["python", "app.py"]  # ✅ FIX: Moved command to correct indentation
        ports:
        - containerPort: 8443 # Or whatever port your polybot app listens on
        env:
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-secrets-manager
              key: telegram_token
        - name: BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: bucket_name
        - name: SQS_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: sqs_url
        - name: POLYBOT_RESULTS_URL
          value: "http://svc-polybot:8443/results"
      imagePullSecrets:
      - name: dockerhub-secret # Points to the dockerhub-secret
