apiVersion: v1
kind: Pod
metadata:
  name: polybot-pod  # Name of your Pod
  namespace: default # Or the namespace you want to create it in
  labels:
    app: polybot
spec:
  containers:
  - name: polybot
    image: docker.io/jeenge/polybot:ms1921
    ports:
    - containerPort: 8443
    env:
    - name: TELEGRAM_TOKEN
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: telegram_token
    - name: BUCKET_NAME
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: bucket_name
    - name: SQS_URL
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: sqs_url
    - name: POLYBOT_RESULTS_URL
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: polybot_results_url
  imagePullSecrets:
  - name: dockerhub-secret
