name: Deploy Polybot (Argo CD)

on:
  push:
    branches:
      - main # Or your main branch
    paths:
      - 'polybotinfra/**' # Trigger when changes are in the polybotinfra folder.

permissions:
  contents: write # Grant write permission to the repository contents

jobs:
  build_push_update_argo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }} # Use REPO_TOKEN instead of GITHUB_TOKEN

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Consider pinning to a specific version:
        # with:
        #   version: v0.11.2

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.io # Or your registry
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Ensure this secret exists in GitHub
          password: ${{ secrets.DOCKERHUB_PASSWORD }} # Ensure this secret exists in GitHub

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./polybotinfra # Path to your Polybot Dockerfile
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/polybot:${{ github.sha }}

      - name: Update Argo CD Image Tag
        run: |
          # Adjust this path if your Polybot deployment YAML is not in ARGOCD/polybotinfra/polybot-deployment.yaml
          sed -i "s|image: .*|image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/polybot:${{ github.sha }}|g" ARGOCD/polybotinfra/polybot-deployment.yaml
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          # Adjust this path if your Polybot deployment YAML is not in ARGOCD/polybotinfra/polybot-deployment.yaml
          git add ARGOCD/polybotinfra/polybot-deployment.yaml
          git commit -m "Update Polybot image tag to ${{ github.sha }} (short SHA: ${{ github.sha[:7] }})"
          git push origin HEAD:${{ github.ref_name }}

      - name: List directory contents
        run: ls -al ARGOCD/polybotinfra/ # Adjust this path if needed

      - name: Logout from Docker registry
        run: docker logout docker.io