name: Deploy Polybot (Argo CD)

on:
  push:
    branches:
     - main
    paths:
      - 'polybot/**' # Only trigger when changes are in the polybot folder.
    issue_comment:
      types: [ created ]

permissions:
  contents: write # Grant write permission to the repository contents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}  # Required for pushing changes

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y yq

      - name: Build and push image
        run: |
          DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}

          if [[ -z $DOCKERHUB_USERNAME ]] || [[ -z $DOCKERHUB_PASSWORD ]]; then
            echo DOCKERHUB_USERNAME and DOCKERHUB_PASSWORD secrets should be configured
            exit 1
          fi

          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          echo "login success"

          cd polybot
          IMAGE_NAME=$DOCKERHUB_USERNAME/polybot:v1.1.${{ github.run_number }}
          docker build --push -t $IMAGE_NAME .
          echo "image build and pushed"

      - name: Update Argo CD Manifest
        run: |
          DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME=$DOCKERHUB_USERNAME/polybot:v1.1.${{ github.run_number }}
          yq -i -y ".spec.template.spec.containers[0].image = \"$IMAGE_NAME\"" ARGOCD/polybotinfra/polybot-deployment.yaml
          echo "Argo CD manifest updated successfully"

      - name: Commit and Push changes
        run: |
           git config --local user.email "github@action"
           git config --local user.name "auto-update"
           git add ARGOCD/polybotinfra/polybot-deployment.yaml
           git commit -m "Update image to $IMAGE_NAME"
           git pull
           git push origin main

      - name: List directory contents
        if: github.event_name == 'push'
        run: ls -al ARGOCD/polybotinfra/ # Replace with the directory containing your yaml.