name: Deploy Polybot

on:
  push:
    branches:
      - main # Or your main branch
    paths:
      - 'polybot/**' # Only trigger when changes are in the polybot folder.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.io # Or your registry
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./polybot # Path to your Polybot Dockerfile
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/polybot:${{ github.sha }} # Tag with commit SHA

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml

      - name: Apply Kubernetes deployment
        run: kubectl apply -f polybot-deployment.yaml # your polybot kubernetes deployment file.
        working-directory: ./k8s # if your polybot kubernetes deployment file is in a k8s folder.