name: Deploy Polybot (Argo CD)

on:
  push:
    branches:
      - main # Or your main branch
    paths:
      - 'polybot/**' # Only trigger when changes are in the polybot folder.
  issue_comment:
    types: [created]

permissions:
  contents: write # Grant write permission to the repository contents

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }} # Use REPO_TOKEN instead of GITHUB_TOKEN

      - name: Check if comment triggers workflow
        if: github.event_name == 'issue_comment'
        run: echo "Workflow triggered by a comment."

      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: docker.io # Or your registry
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Polybot Docker image
        if: github.event_name == 'push'
        run: |
          cd polybotinfra
          IMAGE_NAME=$DOCKERHUB_USERNAME/polybot:${{ github.sha }}
          docker build --push -t $IMAGE_NAME .
          echo "image build and pushed: $IMAGE_NAME"

      - name: Update Argo CD Image Tag
        if: github.event_name == 'push'
        run: |
          IMAGE_NAME=$DOCKERHUB_USERNAME/polybot:${{ github.sha }}
          sed -i "s|image: .*|image: $IMAGE_NAME|g" ARGOCD/polybotinfra/polybot-deployment.yaml
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ARGOCD/polybotinfra/polybot-deployment.yaml
          git commit -m "Update Polybot image to ${{ github.sha }}"
          git push origin HEAD:${{ github.ref_name }}
          echo "Pushed updated Argo CD manifest"

      - name: List directory contents
        if: github.event_name == 'push'
        run: ls -al ARGOCD/polybotinfra/ # Replace with the directory containing your yaml.