name: Deploy YOLO5 and Polybot (Argo CD)

on:
  push:
    branches:
      - main # Or your main branch
    paths:
      - 'yolo5/**'
      - 'polybotinfra/**'
      - 'ARGOCD/yolo5/deployment.yaml'
      - 'ARGOCD/polybotinfra/polybot-deployment.yaml'

permissions:
  contents: write

jobs:
  deploy_yolo5:
    if: github.event_name == 'push' && (startsWith(github.event.commits.*.message, 'yolo5') || contains(github.event.commits.*.modified, 'yolo5') || contains(github.event.commits.*.added, 'yolo5') || contains(github.event.commits.*.removed, 'yolo5') || github.event.paths.* == 'ARGOCD/yolo5/deployment.yaml')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push YOLO5 Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./yolo5
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/yolo5:${{ github.sha }}

      - name: Update YOLO5 Argo CD Image Tag
        run: |
          sed -i "s|image: .*|image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/yolo5:${{ github.sha }}|g" ARGOCD/yolo5/deployment.yaml
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ARGOCD/yolo5/deployment.yaml
          git commit -m "Update YOLO5 image tag to ${{ github.sha }}"
          git push origin HEAD:${{ github.ref_name }}

  deploy_polybot:
    if: github.event_name == 'push' && (startsWith(github.event.commits.*.message, 'polybot') || contains(github.event.commits.*.modified, 'polybotinfra') || contains(github.event.commits.*.added, 'polybotinfra') || contains(github.event.commits.*.removed, 'polybotinfra') || github.event.paths.* == 'ARGOCD/polybotinfra/polybot-deployment.yaml')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Polybot Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./polybotinfra
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/polybot:${{ github.sha }}

      - name: Update Polybot Argo CD Image Tag
        run: |
          sed -i "s|image: .*|image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/polybot:${{ github.sha }}|g" ARGOCD/polybotinfra/polybot-deployment.yaml
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ARGOCD/polybotinfra/polybot-deployment.yaml
          git commit -m "Update Polybot image tag to ${{ github.sha }}"
          git push origin HEAD:${{ github.ref_name }}