name: Deploy YOLO5 (Argo CD)

on:
  push:
    branches:
      - main # Or your main branch
    paths:
      - 'yolo5/**' # Only trigger when changes are in the yolo5 folder.
  issue_comment:
    types: [created]

permissions:
  contents: write # Grant write permission to the repository contents

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }} # Use REPO_TOKEN instead of GITHUB_TOKEN

      - name: Check if comment triggers workflow
        if: github.event_name == 'issue_comment'
        run: echo "Workflow triggered by a comment."

      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: docker.io # Or your registry
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push YOLO5 Docker image
        if: github.event_name == 'push'
        run: |
          cd yolo5
          echo "DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}"
          IMAGE_NAME=$DOCKERHUB_USERNAME/yolo5:${{ github.sha }}
          echo "IMAGE_NAME: $IMAGE_NAME"
          docker build --push -t $IMAGE_NAME .
          echo "image build and pushed: $IMAGE_NAME"

      - name: Update Argo CD Image Tag
        if: github.event_name == 'push'
        run: |
          sed -i "s|image: .*|image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/yolo5:${{ github.sha }}|g" ARGOCD/yolo5/deployment.yaml # Corrected path
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ARGOCD/yolo5/deployment.yaml # Corrected path
          git commit -m "Update YOLO5 image tag to ${{ github.sha }}"
          git pull origin main --rebase
          git push origin HEAD:${{ github.ref_name }} # Push changes to the same branch.
          echo "Pushed updated Argo CD manifest"

      - name: List directory contents
        if: github.event_name == 'push'
        run: ls -al ARGOCD/yolo5/ # Replace with the directory containing your yaml.