name: Deploy YOLO5 (Argo CD)

on:
  push:
    branches:
      - main # Or your main branch
    paths:
      - 'yolo5/**' # Only trigger when changes are in the yolo5 folder.

permissions:
  contents: write # Grant write permission to the repository contents

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }} # Use REPO_TOKEN instead of GITHUB_TOKEN

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.io # Or your registry
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./yolo5 # Path to your YOLO5 Dockerfile (adjust if needed)
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/yolo5:${{ github.sha }}

      - name: Update Argo CD Image Tag
        run: |
          sed -i "s|image: .*|image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/yolo5:${{ github.sha }}|g" ARGOCD/yolo5/deployment.yaml # Corrected path
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ARGOCD/yolo5/deployment.yaml # Corrected path
          git commit -m "Update YOLO5 image tag to ${{ github.sha }}"
          git push origin HEAD:${{ github.ref_name }} # Push changes to the same branch.

      - name: List directory contents
        run: ls -al ARGOCD/yolo5/ # Replace with the directory containing your yaml.